### ISSUE TITLE
Extraneous variable declarations

### ISSUE THREAD

**Issue by gusmccallum** [joshuali7536/LennahSSG#4]
This logic could be more concise and done with less variable declarations.

![image](https://user-images.githubusercontent.com/61558904/133714423-22357ac6-18dc-4c50-b3dd-7f10d07f93a4.png)

**Comment by joshuali7536** [comment]
Some of the variable declarations were done purposely because of how substring works. In order to get the name of the file without the extension it is needed to make a string with the extension (`base_filename`), otherwise it is messier to figure out the length of the name is for the `substr()` function.

`p` is there to keep the length calculation separate from the `file_without_extension` declaration cleaner.
